### ISSUE TITLE
Informal Dinner at Golden Cafe (Craig Road)

### ISSUE THREAD

**Issue by thenglee** [reddotrubyconf/rdrc2017-website#33]
Hi all!

We would like to bring you to Tanjong Pagar to try out our local [zi char](https://en.wikipedia.org/wiki/Tze_Char) for dinner on 21 June (Wed). 

As most speakers are staying at [Amara hotel](http://singapore.amarahotels.com), @laurenceputra will be at the hotel foyer at 6pm to bring everyone to [Golden Cafe](https://www.google.com.sg/maps/place/Golden+Cafe/@1.2775393,103.8410244,17.06z/data=!4m5!3m4!1s0x31da196d1ef0e847:0x479f8bc4d72bf897!8m2!3d1.2775375!4d103.8430604). The walk to Golden Cafe is about 10mins long. Some queuing time is expected so Laurence will depart Amara hotel promptly at 6:15pm :)

Do note that the restaurant is not halal certified but has non-meat options. 

We will also go have some durian after dinner!

If you would like to join us, please drop 👍 as a new _comment_ here so that we can make the necessary arrangements :)

**Comment by JuanitoFatas** [comment]
❣️

**Comment by laurenceputra** [comment]
👍

**Comment by davydovanton** [comment]
👍💗

**Comment by thenglee** [comment]
👍 Matz and Betsy will be coming too :)

**Comment by shujin** [comment]
👍

**Comment by thenglee** [comment]
👍  Nick will be joining us as well!

**Comment by jodeci** [comment]
👍 👍 👍  +3 from 5xRuby joining in!

**Comment by marionschleifer** [comment]
👍 Joining, but probably a little later :)

**Comment by matthewd** [comment]
👍🏻

**Comment by kntsoriano** [comment]
:+1:

**Comment by neilmarion** [comment]
:+1:

**Comment by arnvald** [comment]
👍

**Comment by matadon** [comment]
Would love to, but I'm stuck in Shanghai due to a flight delay. 😭

**Comment by thenglee** [comment]
@matadon aww :( we will miss you. Hope to see you at the speakers dinner on Day 1 :)

**Comment by thenglee** [comment]
👍 Aaron will be coming too!

**Comment by sunkai612** [comment]
👍🏼

**Comment by matadon** [comment]
@thenglee me too!

**Comment by estolfo** [comment]
in!
