### ISSUE TITLE
Add dark background contrast for white navbar text

### ISSUE THREAD

**Issue by luyangkenneth** [reddotrubyconf/rdrc2017-website#6]
Hello! I happened to be browsing the [conference website](http://www.reddotrubyconf.com/) and I noticed that the white text in the navbar doesn't show up nicely when you scroll further down (see screenshot below).

<img width="1478" alt="screen shot 2017-02-15 at 11 58 43 pm" src="https://cloud.githubusercontent.com/assets/9073504/22982822/2e66a676-f3db-11e6-80e7-214550376f0a.png">

I guess the simplest fix would be to set a dark `background-color` for the navbar, especially when the links already have a fade in/out hover transition.

May I create a PR for this? It would be my first contribution to a public repo 😄

**Comment by hanmd82** [comment]
Hi @luyangkenneth, this would be very much appreciated! Are you familiar with the process for doing so?

**Comment by luyangkenneth** [comment]
Yes, I think so!

**Comment by hanmd82** [comment]
Great! Please give it a go!

**Comment by Drenmi** [comment]
Just ping me on Slack if you have questions @luyangkenneth. 😀

**Comment by luyangkenneth** [comment]
Hehe sure 😂 Thanks Ted!

**Comment by luyangkenneth** [comment]
@hanmd82 @Drenmi I've chosen `darkred` for the `background-color`. Would like to seek your opinions on the stylistic choices before I submit my PR.

Here's how it looks:

<img width="959" alt="screen shot 2017-02-16 at 4 33 21 pm" src="https://cloud.githubusercontent.com/assets/9073504/23013468/ae52707e-f465-11e6-91ed-59404edfc9b1.png">

---

<img width="923" alt="screen shot 2017-02-16 at 3 55 16 pm" src="https://cloud.githubusercontent.com/assets/9073504/23013447/97dbecbc-f465-11e6-87b7-a2d3f7eb306e.png">

---

The next question is what we'd like the `a:hover` to look like. I'm inclined to go with option 2. Please let me know your preference, and if you have any further suggestions 🙂

1. `darkred` text color
<img width="921" alt="screen shot 2017-02-16 at 3 55 44 pm" src="https://cloud.githubusercontent.com/assets/9073504/23013536/0ce5b0b0-f466-11e6-9808-3013a9b69f8e.png">

---

2. `darkred` text color with `border: none`
<img width="920" alt="screen shot 2017-02-16 at 3 56 22 pm" src="https://cloud.githubusercontent.com/assets/9073504/23013537/1051d512-f466-11e6-9298-059766ac5fde.png">

---

3. Original `#333333` text color
<img width="914" alt="screen shot 2017-02-16 at 3 55 31 pm" src="https://cloud.githubusercontent.com/assets/9073504/23013623/672d5c1c-f466-11e6-8dd0-526a5bd5a96f.png">

**Comment by hanmd82** [comment]
Hi @luyangkenneth, regarding the top nav bar, would adding some transparency make it look better? Currently the solid nav bar may look jarring - what do you think?

For `a:hover`, I think option 2 (`darkred` text color with `border: none`) looks most suitable.

Please feel free to go ahead and create the PR first - we can try it out on local machine. If there are any changes needed, we can provide feedback using the PR review mechanism. Thanks!

**Comment by luyangkenneth** [comment]
@hanmd82 Yep I agree it's a little jarring at the moment. I'll see what I can do! 🙂
