### ISSUE TITLE
Fix responsive alignment of speaker profiles

### ISSUE THREAD

**Issue by luyangkenneth** [reddotrubyconf/rdrc2017-website#9]
Currently 3 speakers are displayed per row, but this doesn't play well with browser widths of less than 992px:

<img width="600" alt="screen shot 2017-02-16 at 5 08 34 pm" src="https://cloud.githubusercontent.com/assets/9073504/23014636/bfb125f4-f46a-11e6-9541-51b2190b0fbf.png">

I also dug into the code and saw that the speakers are rendered like this:

```slim
section#speakers
  .container
    h2.section-header
      ' Invited Speakers
      .line
    .row.keynote-speakers
      .col-sm-12.text-center
        - Speaker.find_by_identifiers(:matz, :tenderlove, :apotonick).each do |speaker|
          .speaker
            .speaker--avatar
              = image_tag speaker.avatar
            .speaker--info
              .speaker--name
                = speaker.name
              .speaker--tagline
                = speaker.tagline.html_safe
      .col-sm-12.text-center.m-t
        - Speaker.find_by_identifiers(:amatsuda, :betsyhaibel, :emilystolfo).each do |speaker|
          .speaker
            .speaker--avatar
              = image_tag speaker.avatar
            .speaker--info
              .speaker--name
                = speaker.name
              .speaker--tagline
                = speaker.tagline.html_safe
```

which is not very dry if (/ when?) more speakers are added in the future.

Perhaps a better approach would be to extract these into a partial and align the speakers using a center-aligned flexbox?

**Comment by hanmd82** [comment]
Thanks for your feedback @luyangkenneth. There are the invited speakers and we will not add any more invited speakers to the list. The responsive UI effect for smaller screen sizes (i.e. for mobile screens) is not a big issue, as the speaker order and layout are both intentional.
